server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8080
          predicates:
            - Path=/api/student/**
        - id: course
          uri: http://localhost:8081
          predicates:
            - Path=/api/course/**


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

